version: '3.8'

services:
  flask:
    restart: always
    container_name: flask
    build:
      context: ./server
    command: gunicorn -w 2 --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
  react_nginx:
    restart: always
    container_name: react_nginx
    build:
      context: ./ui
    volumes:
      - ./ui/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/.env.docker:/app/.env.local
    ports:
      - "3000:3000"